[package]
name = "one_weekend"
version = "0.1.0"
authors = ["Matthijs De Smedt <matthijsds@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.2"
crossbeam = "0.6"
crossbeam-channel = "0.4"
glam = "0.13.0"
rayon = "1.5"
bvh = "0.4.0"
rand = "0.8.3"
spiral = "0.1.9"
png = "0.16.8"

[profile.release]
lto = true
codegen-units = 1
